---
version: 2

tasks:
  default:
    cmds:
      - task --list

  lint:
    cmds:
      - docker run -tv "$PWD:/mnt" koalaman/shellcheck:v0.5.0
        --color=always --shell=bash --exclude=SC2016
        **/*.sh
  lint-dockerfile:
    cmds:
      - docker run --rm -v $PWD:/app -w /app hadolint/hadolint:latest-debian
        sh -c "find . -name Dockerfile | xargs -L1 hadolint"

  test-single:
    cmds:
      - docker-compose -f {{ .DOCKERFILE_DIR }}/docker-compose.test.yml build
      - docker-compose -f {{ .DOCKERFILE_DIR }}/docker-compose.test.yml run --rm sut
    vars:
      DOCKERFILE_DIR: "src/{{ .PHP_VERSION }}/{{ .OS_VERSION }}/{{ .IMAGE_VARIANT }}"

  test:
    cmds:
      - task: lint
      - task: test-single
        vars:
          PHP_VERSION: 7.4
          OS_VERSION: alpine
          IMAGE_VARIANT: cli
      - task: test-single
        vars:
          PHP_VERSION: 7.4
          OS_VERSION: alpine
          IMAGE_VARIANT: fpm
      - task: test-single
        vars:
          PHP_VERSION: 7.3
          OS_VERSION: alpine
          IMAGE_VARIANT: cli
      - task: test-single
        vars:
          PHP_VERSION: 7.2
          OS_VERSION: alpine
          IMAGE_VARIANT: cli
      - task: test-single
        vars:
          PHP_VERSION: 7.1
          OS_VERSION: alpine
          IMAGE_VARIANT: cli
      - task: test-single
        vars:
          PHP_VERSION: 7.0
          OS_VERSION: alpine
          IMAGE_VARIANT: cli
      - task: test-single
        vars:
          PHP_VERSION: 5.6
          OS_VERSION: alpine
          IMAGE_VARIANT: cli
