---
version: 2

tasks:
  default:
    cmds:
      - task --list

  lint:
    cmds:
      - docker run -tv "$PWD:/mnt" koalaman/shellcheck:v0.5.0
        --color=always --shell=bash --exclude=SC2016
        **/*.sh

  test-single:
    cmds:
      - docker-compose -f {{ .DOCKERFILE_DIR }}/docker-compose.test.yml build
      - docker-compose -f {{ .DOCKERFILE_DIR }}/docker-compose.test.yml run sut
    vars:
      DOCKERFILE_DIR: "src/{{ .PHP_VERSION }}/{{ .OS_VERSION }}/{{ .IMAGE_VARIANT }}"

  test:
    cmds:
      - task: lint
      - task: test-single
        vars:
          PHP_VERSION: 7.1
          OS_VERSION: alpine
          IMAGE_VARIANT: cli
      - task: test-single
        vars:
          PHP_VERSION: 7.0
          OS_VERSION: alpine
          IMAGE_VARIANT: cli
      - task: test-single
        vars:
          PHP_VERSION: 5.6
          OS_VERSION: alpine
          IMAGE_VARIANT: cli
