---
version: 2

tasks:
  default:
    cmds:
      - task --list

  test-single:
    cmds:
      - docker-compose -f {{ .DOCKERFILE_DIR }}/docker-compose.test.yml build
      - docker-compose -f {{ .DOCKERFILE_DIR }}/docker-compose.test.yml run sut
    vars:
      DOCKERFILE_DIR: "{{ .PHP_VERSION }}/{{ .OS_VERSION }}/{{ .IMAGE_VARIANT }}"

  test:
    cmds:
      - task: test-single
        vars:
          PHP_VERSION: 5.6
          OS_VERSION: alpine
          IMAGE_VARIANT: cli
