---
version: 2

tasks:
  default:
    cmds:
      - task --list

  build-single:
    cmds:
      - docker build
        -f {{ .PHP_VERSION }}/{{ .OS_VERSION }}/{{ .IMAGE_VARIANT }}/Dockerfile
        -t antonmarin/php:{{ .PHP_VERSION }}-{{ .OS_VERSION }}-{{ .IMAGE_VARIANT }}
        .

  test-single:
    cmds:
      - task: build-single
        vars:
          PHP_VERSION:
            sh: echo {{ .PHP_VERSION }}
          OS_VERSION:
            sh: echo {{ .OS_VERSION }}
          IMAGE_VARIANT:
            sh: echo {{ .IMAGE_VARIANT }}
      - docker-compose -f {{ .PHP_VERSION }}/{{ .OS_VERSION }}/{{ .IMAGE_VARIANT }}/docker-compose.test.yml run sut

  test:
    cmds:
      - task: test-single
        vars:
          PHP_VERSION: 5.6
          OS_VERSION: alpine
          IMAGE_VARIANT: cli
