---
version: "3.5"
services:
  sut:
    build:
      context: ../../..
      dockerfile: 8.1/alpine/cli/Dockerfile
    volumes:
      - ../../../../tests:/tmp/tests
    command: /tmp/tests/suite_cli.sh
