---
version: "3.5"
services:
  sut:
    build:
      context: ../../..
      dockerfile: 7.4/alpine/fpm/Dockerfile
    image: fpm_sut
    volumes:
      - ../../../../tests:/tmp/tests
    command: /tmp/tests/suite_fpm.sh
    depends_on:
      - fpm
      - fpm-alternative
  fpm:
    build:
      context: ../../..
      dockerfile: 7.4/alpine/fpm/Dockerfile
    volumes:
      - ../../../../tests/test.php:/var/www/html/test.php
    env_file: ../../../../tests/.env_default
  fpm-alternative:
    build:
      context: ../../..
      dockerfile: 7.4/alpine/fpm/Dockerfile
    volumes:
      - ../../../../tests/test.php:/var/www/html/test.php
    env_file: ../../../../tests/.env_alternative
    command:
      - php-fpm
      - -d
      - zend_extension=xdebug.so
