name: default
on: [push]
jobs:
  lint-dockerfile:
    name: Validate dockerfile best practices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        run: make lint-dockerfile
  lint-shell:
    name: Validate shell scripts best practices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        run: make lint-shell
  test:
    name: Test and publish images
    strategy:
      matrix:
        php: [7.4, 7.3, 7.2, 7.1, "7.0"]
        variant: [cli, fpm]
    runs-on: ubuntu-latest
    needs: [lint-shell, lint-dockerfile]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test image
        run: make PHP_VERSION=${{ matrix.php }} IMAGE_VARIANT=${{ matrix.variant}} OS_VERSION=alpine test-single
      - name: Publish image
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u antonmarin --password-stdin
          make PHP_VERSION=${{ matrix.php }} IMAGE_VARIANT=${{ matrix.variant}} OS_VERSION=alpine publish
