name: default
on: [push]
jobs:
  lint-dockerfiles:
    name: Validate dockerfile best practices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hadolint
        run: make lint-dockerfile
